language: go

go:
  - 1.5

go_import_path: github.com/deis/makeup

install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.8.3/glide-0.8.3-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-0.8.3-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH" GLIDE_HOME="$HOME/.glide"

script: make build

before_deploy: make pre-publish

deploy:
- provider: bintray
  file: build/ci/bintray-ci.json
  user: sgoings
  key:
    secure: "OoB7zeP22Jt0DB57GjzL06y1rrlnPjhgulbAUkBRclU9jzxDcM3yAX9BSlHY6DlArzuob6cRegqn8kGvnIWUY3Xcn+82nl5ZW5lUpT2OXaGvNI1dX8ymfmOTxDYiRIcGQ8E0d3+66YYLkhwm/UvC80rvDAiG1ShGojwTQdBN1YYOP2tSi/SMgumlWjBLdCWn3yoni2ujGkfsB131Y/kOanRIIZDAwVx570qCkYwum9LCjo0VVXWCzXtoVFKfye7mly9FPqvsQf3zhNUkNdZl84jZfJuE04y9gaSbhHpDwVwbQB7dWPlkjWXSwobxXGVp9IlnitlB9JWbCavUiffYmP0j0/bBdYS2lrbURLkr52Jlm3ikpJtgiGSppHdcLgo4i8UX3iXBZ8jms0Pu/ZRcEWWRwJfYESMZR/ijZoL1vF2+fLELbrS41rnzoulJoOBtFqhc4Zpy/zKleANb0Pj1TQYEbUZAYACEksdJIpCe8nY6WjP1JvNOBpQHd05XB9OX1iqcOUleU1M9lyi0K7QDa2AQTSxhTE9bnuAHlB8arvVS17qeXCeteI4DSYSCZftMXuedfBZhDRdWdirgmq6PJ9RBuSZde3E9DMRd/Z+qIVefDjZ18fRjxsr+J82gz9vtxfTLPWFyzafyKKD1h6O48X0Wk/szKyP4cxNtgKqDFZw="
  on:
    all_branches: true
